
없어진 기록 찾기
SELECT O.ANIMAL_ID, O.NAME FROM ANIMAL_OUTS O
LEFT JOIN ANIMAL_INS I ON
O.ANIMAL_ID = I.ANIMAL_ID WHERE I.ANIMAL_ID IS NULL;


보호 시작일보다 입양일이 더 빠른
SELECT I.ANIMAL_ID, I.NAME FROM ANIMAL_INS I 
JOIN ANIMAL_OUTS O ON
I.ANIMAL_ID = O.ANIMAL_ID WHERE I.DATETIME > O.DATETIME
ORDER BY I.DATETIME ASC;

아직 입양을 못 간 동물 중, 가장 오래 보호소에 있었던 동물 3마리
SELECT I.NAME, I.DATETIME FROM ANIMAL_INS I
LEFT JOIN ANIMAL_OUTS O
ON I.ANIMAL_ID = O.ANIMAL_ID WHERE O.ANIMAL_ID IS NULL
ORDER BY DATETIME LIMIT 3;

보호소에 들어올 당시에는 중성화1되지 않았지만, 보호소를 나갈 당시에는 중성화된 동물
SELECT i.ANIMAL_ID, i.ANIMAL_TYPE, i.NAME FROM ANIMAL_INS I
JOIN ANIMAL_OUTS O ON I.ANIMAL_ID = O.ANIMAL_ID
WHERE I.SEX_UPON_INTAKE != O.SEX_UPON_OUTCOME;