

동물 보호소에 들어온 모든 동물의 정보를 ANIMAL_ID순으로 조회
SELECT * FROM ANIMAL_INS;

역순으로 정렬
SELECT NAME, DATETIME FROM ANIMAL_INS ORDER BY ANIMAL_ID DESC;

조건문
SELECT ANIMAL_ID, NAME FROM ANIMAL_INS WHERE INTAKE_CONDITION = 'SICK';

조건문(~가 아닐 경우 찾기)
SELECT ANIMAL_ID, NAME FROM ANIMAL_INS WHERE INTAKE_CONDITION != 'Aged';

단, 이름이 같은 동물 중에서는 보호를 나중에 시작한 동물을 먼저 
SELECT ANIMAL_ID, NAME, DATETIME FROM ANIMAL_INS ORDER BY NAME ASC, DATETIME DESC;

상위 N개 레코드 
SELECT NAME FROM ANIMAL_INS ORDER BY DATETIME LIMIT 1;